### Register a New User - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/auth/register
Content-Type: application/json

{
  "username": "testuser2",
  "password": "testpassword2",
  "adminRequest": false
}

### Register a New Admin User (Pending Approval) - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/auth/register
Content-Type: application/json

{
  "username": "adminuser2",
  "password": "adminpassword2",
  "adminRequest": true
}

### Login with Registered User - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/auth/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "testpassword2"
}

> {% client.test("Extract Token", function() {
        var response = JSON.parse(responseBody);
        client.global.set("jwt_token", response.token);
    }); %}

### Login with Admin User - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/auth/login
Content-Type: application/json

{
  "username": "adminuser",
  "password": "adminpassword"
}

> {% client.test("Extract Admin Token", function() {
        var response = JSON.parse(responseBody);
        client.global.set("jwt_token_admin", response.token);
    }); %}

### Get All Products - true
GET http://localhost:1488/lab1-1.0-SNAPSHOT/api/products?page=1&size=10&filterBy=owner.name&filter=abobik&sortBy=price&
    sortDirection=ASC
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjUzMDgsImV4cCI6MTczMjkxMTcwOH0.aBgCjve-mSB31cCchFtq_cXXeWTDL2ZLSwm0YFyNKeg
Accept: application/json

### Get Imports - true
GET http://localhost:1488/lab1-1.0-SNAPSHOT/api/import
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjUzMDgsImV4cCI6MTczMjkxMTcwOH0.aBgCjve-mSB31cCchFtq_cXXeWTDL2ZLSwm0YFyNKeg
Accept: application/json

### Massive create Products
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/import
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjE0NDAsImV4cCI6MTczMjkwNzg0MH0.WLvEwsJgtSsVhwbTFm9sPeMbrTq5c-XM9CHmbjgBrZw
Content-Type: application/json

{
  "products": [
    {
      "name": "Dota72",
      "coordinates": {
        "x": 5,
        "y": 100
      },
      "unitOfMeasure": "METERS",
      "price": 20,
      "manufactureCost": 150.0,
      "rating": 5,
      "owner": {
        "id": 1
      },
      "manufacturer": {
        "id": 1
      }
    },
    {
      "name": "Dota33",
      "coordinates": {
        "x": 10,
        "y": 200
      },
      "unitOfMeasure": "MILLILITERS",
      "price": 30,
      "manufactureCost": 200.0,
      "rating": 4,
      "owner": {
        "id": 1
      },
      "manufacturer": {
        "id": 1
      }
    }
  ]
}


### Create a New Products - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjE0NDAsImV4cCI6MTczMjkwNzg0MH0.WLvEwsJgtSsVhwbTFm9sPeMbrTq5c-XM9CHmbjgBrZw
Content-Type: application/json

{
  "name": "Dota722222",
  "coordinates": {
    "x": 5,
    "y": 100
  },
  "unitOfMeasure": "METERS",
  "price": 20,
  "manufactureCost": 150.0,
  "rating": 5,
  "owner": {
    "id": 1
  }
}

### Create a New Person - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/persons
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjE0NDAsImV4cCI6MTczMjkwNzg0MH0.WLvEwsJgtSsVhwbTFm9sPeMbrTq5c-XM9CHmbjgBrZw
Content-Type: application/json

{
  "name": "abobik",
  "eyeColor": "GREEN",
  "hairColor": "BLUE",
  "birthday": "1990-01-01T12:00:00",
  "location": {
    "x": 10,
    "y": 20,
    "z": 30
  },
  "nationality": "USA"
}

### Create a New Organization - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/organizations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE3MzI4MjUzMDgsImV4cCI6MTczMjkxMTcwOH0.aBgCjve-mSB31cCchFtq_cXXeWTDL2ZLSwm0YFyNKeg
Content-Type: application/json

{
  "name": "Mojang",
  "annualTurnover": 15000.0,
  "employeesCount": 50,
  "rating": 5,
  "type":"COMMERCIAL"
}

### Update a Products - true
PUT http://localhost:1488/lab1-1.0-SNAPSHOT/api/products/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMDQ5NzQyOSwiZXhwIjoxNzMwNTgzODI5fQ.GABkrTm7aXphbar5OTpG7l5qwx6yEjsm0q9cWKKQ4VQ
Content-Type: application/json

{
  "id": 4,
  "name": "Dota142229",
  "coordinates": {
    "x": 5,
    "y": 110
  },
  "unitOfMeasure": "METERS",
  "price": 20,
  "manufactureCost": 150.0,
  "rating": 5,
  "owner": {
    "id": 1
  }
}

### Delete a Product - true
DELETE http://localhost:1488/lab1-1.0-SNAPSHOT/api/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzMwNDcwNDc1LCJleHAiOjE3MzA1NTY4NzV9.kgbgDUG6aT7fZxHwsD6uzyNpeID-l2GfXcrOH9F0IMU

### Delete a Person - true
DELETE http://localhost:1488/lab1-1.0-SNAPSHOT/api/persons/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5MzI2NTQzLCJleHAiOjE3Mjk0MTI5NDN9.9kX1D8xQRWcfuLp8rsNnK3qKwbAKsmrOeo3QbOU9gWg

### Approve Pending Admin User - true
POST http://localhost:1488/lab1-1.0-SNAPSHOT/api/auth/approve-admin/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbnVzZXIiLCJyb2xlIjoiQURNSU4iLCJpZCI6MiwiaWF0IjoxNzMyODI1ODk0LCJleHAiOjE3MzI5MTIyOTR9.0WT907WbOqqZUpVffFh65l5vI_Yel7C09jNPnuukef0

### Get All rating above
GET http://localhost:1488/lab1-1.0-SNAPSHOT/api/products/rating-above?minRating=4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzMwNDcwNDc1LCJleHAiOjE3MzA1NTY4NzV9.kgbgDUG6aT7fZxHwsD6uzyNpeID-l2GfXcrOH9F0IMU

### Get procent increase
GET http://localhost:1488/lab1-1.0-SNAPSHOT/api/products/increase-price?percentage=10.0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzMwNDcwNDc1LCJleHAiOjE3MzA1NTY4NzV9.kgbgDUG6aT7fZxHwsD6uzyNpeID-l2GfXcrOH9F0IMU